## Uso inicial de numpy

In [8]:
import numpy as np

a = np.array([1,2,3,4,5])
b = np.arange(10)
c = np.linspace(0, 2, 5)

print("transformacion de la lista de python en array de np", a)
print("array de np generado de manera secuencial", b)
print("un array de numeros equidistantes", c)

transformacion de la lista de python en array de np [1 2 3 4 5]
array de np generado de manera secuencial [0 1 2 3 4 5 6 7 8 9]
un array de numeros equidistantes [0.  0.5 1.  1.5 2. ]


### Trabajando con array 1D

In [12]:
import numpy as np

array = np.arange(20)
sub_arr = array[6:20]

print("sub-array desde el 6 al 19", sub_arr)

print("ultimo elemento", array[-1])
print("primer elemento", array[0])

sub-array desde el 6 al 19 [ 6  7  8  9 10 11 12 13 14 15 16 17 18 19]
ultimo elemento 19
primer elemento 0


In [14]:
import numpy as np

arr   = np.array([10, 11, 12, 13, 14])
arr2  = np.array([1, 2, 3, 4, 5])

suma  = arr + arr2
mult   = arr2 * arr 

print("multiplicacion de las matrices", mult)
print("suma de las matrices", suma)

multiplicacion de las matrices [10 22 36 52 70]
suma de las matrices [11 13 15 17 19]


### Trabajando con arrays 2D

In [28]:
import numpy as np

A = np.array([[10, 30, 50],
             [20, 40, 60],
             [200,400,600]])

c = np.array([1,2,3])

print("Resultado del broadcasting\n", A + c)

B = np.array([[1, 3, 5],
             [2, 4, 6],
             [100,300,500]])

producto = np.dot(A, B)
determinante = np.linalg.det(B)
print("Producto de A * B\n", producto)
print("Transpuesta de A\n", A.T)
print("Determinante de A\n", determinante)

Resultado del broadcasting
 [[ 11  32  53]
 [ 21  42  63]
 [201 402 603]]
Producto de A * B
 [[  5070  15150  25230]
 [  6100  18220  30340]
 [ 61000 182200 303400]]
Transpuesta de A
 [[ 10  20 200]
 [ 30  40 400]
 [ 50  60 600]]
Determinante de A
 0.0


### Estadistica y manipulacion de datos

In [ ]:
import numpy as np

datos = np.random.rand(100)

media = np.mean(datos)
mediana = np.median(datos)
desviacion = np.std(datos);