## Uso inicial de numpy

In [ ]:
import numpy as np

transpuesta = np.array([1,2,3,4,5])
b = np.arange(10)
c = np.linspace(0, 2, 5)

print("transformacion de la lista de python en array de np", transpuesta)
print("array de np generado de manera secuencial", b)
print("un array de numeros equidistantes", c)

transformacion de la lista de python en array de np [1 2 3 4 5]
array de np generado de manera secuencial [0 1 2 3 4 5 6 7 8 9]
un array de numeros equidistantes [0.  0.5 1.  1.5 2. ]


### Trabajando con array 1D

In [12]:
import numpy as np

array = np.arange(20)
sub_arr = array[6:20]

print("sub-array desde el 6 al 19", sub_arr)

print("ultimo elemento", array[-1])
print("primer elemento", array[0])

sub-array desde el 6 al 19 [ 6  7  8  9 10 11 12 13 14 15 16 17 18 19]
ultimo elemento 19
primer elemento 0


In [14]:
import numpy as np

arr   = np.array([10, 11, 12, 13, 14])
arr2  = np.array([1, 2, 3, 4, 5])

suma  = arr + arr2
mult   = arr2 * arr 

print("multiplicacion de las matrices", mult)
print("suma de las matrices", suma)

multiplicacion de las matrices [10 22 36 52 70]
suma de las matrices [11 13 15 17 19]


### Trabajando con arrays 2D

In [ ]:
import numpy as np

matriz = np.array([[10, 30, 50],
             [20, 40, 60],
             [200,400,600]])

c = np.array([1,2,3])

print("Resultado del broadcasting\n", matriz + c)

B = np.array([[1, 3, 5],
             [2, 4, 6],
             [100,300,500]])

producto = np.dot(matriz, B)
determinante = np.linalg.det(B)
print("Producto de A * B\n", producto)
print("Transpuesta de A\n", matriz.T)
print("Determinante de A\n", determinante)

Resultado del broadcasting
 [[ 11  32  53]
 [ 21  42  63]
 [201 402 603]]
Producto de A * B
 [[  5070  15150  25230]
 [  6100  18220  30340]
 [ 61000 182200 303400]]
Transpuesta de A
 [[ 10  20 200]
 [ 30  40 400]
 [ 50  60 600]]
Determinante de A
 0.0


### Estadistica y manipulacion de datos

In [13]:
import numpy as np

datos = np.random.rand(100)

media = np.mean(datos)
mediana = np.median(datos)
desviacion = np.std(datos)

print("Media", media)
print("Mediana", mediana)
print("Desviacion estandar", desviacion)

Media 0.513599688830057
Mediana 0.5060046575136905
Desviacion estandar 0.2817631243107107


### Ejercicio 1: Analisis de una matriz de  datos

In [10]:
import numpy as np

matriz = np.random.randint(50, size = (5, 5))


print("Matriz original\n", matriz)

sum_rows        = np.sum(matriz, axis = 1)
sum_cols        = np.sum(matriz, axis = 0)
print("\nSuma de filas", sum_rows)
print("\nSuma de Columnas", sum_cols)

# max_cols        = np.max(A, axis = 0)
max_rows        = np.max(matriz, axis = 1)
print("\nValor maximo de cada fila", max_rows)

diagonal        = np.diag(matriz)
sum_diagonal    = np.sum(diagonal)
print("\nSuma de la diagonal principal", sum_diagonal)

transpuesta = matriz.T
result          = np.dot(matriz, transpuesta)
print("\nProducto de la matriz original y su transpuesta\n", result)

Matriz original
 [[ 9 37  7 24 11]
 [34 34 25 49 28]
 [33 22 46 25 32]
 [20 11 12  4 23]
 [49  1 40  4 42]]

Suma de filas [ 88 170 158  70 136]

Suma de Columnas [145 105 130 106 136]

Valor maximo de cada fila [37 49 46 23 49]

Suma de la diagonal principal 135

Producto de la matriz original y su transpuesta
 [[2196 3223 2385 1020 1316]
 [3223 6122 5141 2194 4072]
 [2385 5141 5338 2290 4923]
 [1020 2194 2290 1210 2453]
 [1316 4072 4923 2453 5782]]


### Ejercicio 2: Estadísticas y Normalización de Datos

In [ ]:
import numpy as np

matriz = np.random.uniform(0,100, (100, 4))
print("Array original\n", matriz)

media_cols = np.mean(matriz, axis = 0)
mediana_cols = np.median(matriz, axis = 0)
desviacion_cols = np.std(matriz, axis = 0)
print("\nMedia de cada columna", media_cols)
print("\nMediana de cada columna", mediana_cols)
print("\nDesviacion estandar de cada columna", desviacion_cols)

arr_normalize = (matriz - media_cols) / desviacion_cols 
print("\nArray normalizado\n", arr_normalize) 

max_cols = np.max(matriz, axis = 0)[1]
print("\n fila con valor maximo en la segunda columna", max_cols)

Array original
 [[ 7.32635617 14.97334016  4.60422664  5.39382502]
 [59.13576757 92.7913809  92.89287766 74.21411299]
 [14.29086251 76.06003124 11.84859822 85.87641334]
 [35.13495365 19.16083556 47.2274291  74.16174401]
 [13.58918373  4.92182666 25.1125078  70.61885442]
 [12.59307798 70.46301698 51.15714305 34.59037492]
 [54.27780887 96.15573661 30.00644581 57.04285974]
 [33.61499976 30.5804436  35.46311016 90.90047306]
 [ 9.50629691 35.80366031 60.45633924 33.40366297]
 [35.24392985 80.16180164 35.70023906  1.59877842]
 [69.11432442 57.44274781 90.2629624  26.92227153]
 [ 0.10694326  7.78385051 45.15537353 60.17862948]
 [25.07650607 75.95007994 74.93904502 37.66666389]
 [54.02146836 25.22983781 46.47425847 28.47545627]
 [81.72667699 90.18274793 42.07054538 49.116772  ]
 [ 7.82359028 70.05373248 80.59605103 53.57879985]
 [52.17972215 97.82715255  1.92619547 98.24481353]
 [88.04722684 74.82493716 54.2224313  48.96278042]
 [70.63344831  5.16519056 61.48998079 72.07318877]
 [30.10973528 1